/* Generated by bin2c, do not edit manually */
#ifndef __background_h_included
#define __background_h_included

/* Contents of file background.png */
extern const long int background_png_size;
extern const unsigned char background_png[135257];

#endif    /* __background_h_included */
