/* Generated by bin2c, do not edit manually */
#ifndef __brick2_h_included
#define __brick2_h_included

/* Contents of file brick2.png */
extern const long int brick2_png_size;
extern const unsigned char brick2_png[1042];

#endif    /* __brick2_h_included */
