/* Generated by bin2c, do not edit manually */
#ifndef __brick6_h_included
#define __brick6_h_included

/* Contents of file brick6.png */
extern const long int brick6_png_size;
extern const unsigned char brick6_png[1056];

#endif    /* __brick6_h_included */
