/* Generated by bin2c, do not edit manually */
#ifndef __brick1_h_included
#define __brick1_h_included

/* Contents of file brick1.png */
extern const long int brick1_png_size;
extern const unsigned char brick1_png[855];

#endif    /* __brick1_h_included */
