/* Generated by bin2c, do not edit manually */
#ifndef __brick3_h_included
#define __brick3_h_included

/* Contents of file brick3.png */
extern const long int brick3_png_size;
extern const unsigned char brick3_png[1365];

#endif    /* __brick3_h_included */
