/* Generated by bin2c, do not edit manually */
#ifndef __brick0_h_included
#define __brick0_h_included

/* Contents of file brick0.png */
extern const long int brick0_png_size;
extern const unsigned char brick0_png[208];

#endif    /* __brick0_h_included */
