/* Generated by bin2c, do not edit manually */
#ifndef __brick4_h_included
#define __brick4_h_included

/* Contents of file brick4.png */
extern const long int brick4_png_size;
extern const unsigned char brick4_png[806];

#endif    /* __brick4_h_included */
