/* Generated by bin2c, do not edit manually */
#ifndef __brick5_h_included
#define __brick5_h_included

/* Contents of file brick5.png */
extern const long int brick5_png_size;
extern const unsigned char brick5_png[902];

#endif    /* __brick5_h_included */
