/* Generated by bin2c, do not edit manually */
#ifndef __cursor_h_included
#define __cursor_h_included

/* Contents of file cursor.png */
extern const long int cursor_png_size;
extern const unsigned char cursor_png[343];

#endif    /* __cursor_h_included */
