/* Generated by bin2c, do not edit manually */
#ifndef __cursor_sound_h_included
#define __cursor_sound_h_included

/* Contents of file cursor.wav */
extern const long int cursor_sound_size;
extern const unsigned char cursor_sound[2258];

#endif    /* __cursor_sound_h_included */
