/* Generated by bin2c, do not edit manually */
#ifndef __basicfont_h_included
#define __basicfont_h_included

/* Contents of file basicfont.png */
extern const long int basicfont_size;
extern const unsigned char basicfont[343];

#endif    /* __basicfont_h_included */
