/* Generated by bin2c, do not edit manually */
#ifndef __lightmask_h_included
#define __lightmask_h_included

/* Contents of file lightmask.png */
extern const long int lightmask_png_size;
extern const unsigned char lightmask_png[179];

#endif    /* __lightmask_h_included */
