/* Generated by bin2c, do not edit manually */
#ifndef __pop_sound_h_included
#define __pop_sound_h_included

/* Contents of file pop.wav */
extern const long int pop_sound_size;
extern const unsigned char pop_sound[3866];

#endif    /* __pop_sound_h_included */
